### ISSUE TITLE
Docker compose environment yaml syntax error

### ISSUE THREAD

**Issue by MFYDev** [magicpages/ghost-cache-invalidation-proxy#2]
Hi, did you try to deploy this? 

Seems like according to your readme

```yaml
WEBHOOK_HEADERS={"AccessKey": "${secret}", "Content-Type": "application/json"}
WEBHOOK_BODY_TEMPLATE={"urls": ${urls}}
```

These two lines caused docker compose file syntax error and cannot start. I tried to change it to

```yaml
WEBHOOK_HEADERS: '{"AccessKey": "${secret}", "Content-Type": "application/json"}'
      # Check if ${urls} is specific to the image logic
      WEBHOOK_BODY_TEMPLATE: '{"urls": ${urls}}'
```

However according to the log it is denying from bunny side
